CREATE TABLE APSDATA.ACT_HI_TASKINST
(   ID_                 NVARCHAR2(64) NOT NULL,
    PROC_DEF_ID_        NVARCHAR2(64),
    TASK_DEF_KEY_       NVARCHAR2(255),
    PROC_INST_ID_       NVARCHAR2(64),
    EXECUTION_ID_       NVARCHAR2(64),
    PARENT_TASK_ID_     NVARCHAR2(64),
    NAME_               NVARCHAR2(255),
    DESCRIPTION_        NVARCHAR2(2000),
    OWNER_              NVARCHAR2(255),
    ASSIGNEE_           NVARCHAR2(255),
    START_TIME_         TIMESTAMP (6) NOT NULL,
    CLAIM_TIME_         TIMESTAMP (6),
    END_TIME_           TIMESTAMP (6),
    DURATION_           NUMBER(10),
    DELETE_REASON_      NVARCHAR2(2000),
    PRIORITY_           NUMBER(10),
    DUE_DATE_           TIMESTAMP (6),
    FORM_KEY_           NVARCHAR2(255),
    CATEGORY_           NVARCHAR2(255),
    TENANT_ID_          NVARCHAR2(255) DEFAULT ''
);

CREATE INDEX APSDATA.IDX_ACT_HI_TASKINST_PROC ON APSDATA.ACT_HI_TASKINST (PROC_INST_ID_);
CREATE INDEX APSDATA.IDX_ASSIGNEE ON APSDATA.ACT_HI_TASKINST (ASSIGNEE_);
CREATE INDEX APSDATA.IDX_END_TIME ON APSDATA.ACT_HI_TASKINST (END_TIME_);
CREATE INDEX APSDATA.IDX_ACT_HI_TASKINST_ID ON APSDATA.ACT_HI_TASKINST (ID_)  INITRANS 16;
ALTER TABLE APSDATA.ACT_HI_TASKINST ADD CONSTRAINT PK_ACT_HI_TASKINST PRIMARY KEY (ID_) using index APSDATA.IDX_ACT_HI_TASKINST_ID;
