CREATE TABLE APSDATA.ACT_HI_ACTINST
(   ID_                 NVARCHAR2(64) NOT NULL,
    PROC_DEF_ID_        NVARCHAR2(64) NOT NULL,
    PROC_INST_ID_       NVARCHAR2(64) NOT NULL,
    EXECUTION_ID_       NVARCHAR2(64) NOT NULL,
    ACT_ID_             NVARCHAR2(255) NOT NULL,
    TASK_ID_            NVARCHAR2(64),
    CALL_PROC_INST_ID_  NVARCHAR2(64),
    ACT_NAME_           NVARCHAR2(255),
    ACT_TYPE_           NVARCHAR2(255) NOT NULL,
    ASSIGNEE_           NVARCHAR2(255),
    START_TIME_         TIMESTAMP (6) NOT NULL,
    END_TIME_           TIMESTAMP (6),
    DURATION_           NUMBER(10),
    TENANT_ID_          NVARCHAR2(255) DEFAULT ''
);

CREATE INDEX APSDATA.IDX_ACT_HI_ACTINST_START ON APSDATA.ACT_HI_ACTINST (START_TIME_);
CREATE INDEX APSDATA.IDX_ACT_HI_ACTINST_END ON APSDATA.ACT_HI_ACTINST (END_TIME_);
CREATE INDEX APSDATA.IDX_ACT_HI_ACTINST_PROCACT ON APSDATA.ACT_HI_ACTINST (PROC_INST_ID_, ACT_ID_);
CREATE INDEX APSDATA.IDX_ACT_HI_ACTINST_EXECACT ON APSDATA.ACT_HI_ACTINST (EXECUTION_ID_, ACT_ID_);
CREATE INDEX APSDATA.IDX_ACT_HI_ACTINST_ID ON APSDATA.ACT_HI_ACTINST (ID_) INITRANS 16;
ALTER TABLE APSDATA.ACT_HI_ACTINST ADD CONSTRAINT PK_ACT_HI_ACTINST PRIMARY KEY (ID_) using index APSDATA.IDX_ACT_HI_ACTINST_ID;
