CREATE TABLE APSDATA.ACT_HI_PROCINST
(   ID_                         NVARCHAR2(64) NOT NULL,
    PROC_INST_ID_               NVARCHAR2(64) NOT NULL,
    BUSINESS_KEY_               NVARCHAR2(255),
    PROC_DEF_ID_                NVARCHAR2(64) NOT NULL,
    START_TIME_                 TIMESTAMP (6) NOT NULL,
    END_TIME_                   TIMESTAMP (6),
    DURATION_                   NUMBER(10),
    START_USER_ID_              NVARCHAR2(255),
    START_ACT_ID_               NVARCHAR2(255),
    END_ACT_ID_                 NVARCHAR2(255),
    SUPER_PROCESS_INSTANCE_ID_  NVARCHAR2(64),
    DELETE_REASON_              NVARCHAR2(2000),
    TENANT_ID_                  NVARCHAR2(255) DEFAULT '',
    NAME_                       NVARCHAR2(255)
);

CREATE INDEX APSDATA.IDX_ACT_HI_PROCINST_END ON APSDATA.ACT_HI_PROCINST (END_TIME_);
CREATE INDEX APSDATA.IDX_ACT_HI_PROCINST_BUSKEY ON APSDATA.ACT_HI_PROCINST (BUSINESS_KEY_);
CREATE INDEX APSDATA.IDX_ACT_HI_PROCINST_ID ON APSDATA.ACT_HI_PROCINST (ID_) INITRANS 16;
ALTER TABLE APSDATA.ACT_HI_PROCINST ADD CONSTRAINT PK_ACT_HI_PROCINST PRIMARY KEY (ID_) using index APSDATA.IDX_ACT_HI_PROCINST_ID;
